config/routes.rb
Rails.application.routes.draw do
  # get 'rentals/new'
  # get 'rentals/create'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/dashboard", to: "pages#dashboard", as: "dashboard"
  get "/dashboard/:id", to: "pages#dashboard_booking", as: "dashboard_booking"

  resources :pokemons do
    resources :rentals, only: [:create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :user
  has_many :rentals, dependent: :destroy

  validates :name, presence: true
  validates :special_capacity, presence: true
  validates :category, presence: true
  validates :description, presence: true
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_special_capacity_category,
    against: [ :name, :special_capacity, :category ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :pokemon
  belongs_to :user

# user validation
# has_many :pokemons, dependent: :destroy

  def self.unavailable_dates(pokemon)
    all_rentals = []
    Rental.where(pokemon_id: pokemon.id).each do |data|
      hash = { from: data.rental_beginning.to_s("yyyy-M-dd"), to: data.rental_end.to_s("yyyy-M-dd") }
      all_rentals << hash
    end
    all_rentals
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :pokemons, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def dashboard
    # raise
    @user = current_user
    @pokemons = current_user.pokemons
    @rentals = Rental.where(user_id: current_user.id)
  end

  def dashboard_booking
    @user = current_user
    @pokemons = current_user.pokemons
    @rentals = Rental.where(user_id: current_user.id)
    @last_rental = Rental.find(params[:id])
    render :dashboard
  end

  def home
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    if params[:query].present?
      @pokemons = policy_scope(Pokemon).search_by_name_and_special_capacity_category(params[:query])
    else
      @pokemons = policy_scope(Pokemon)
    end

    @markers = []

    @pokemons.geocoded.each do |pokemon|
      puts "entree de le map"
      puts "pokemon:#{pokemon}"
      puts "current user:#{current_user}"
      puts "user:#{pokemon.user}"
      if pokemon.user != current_user
        @markers << {
          lat: pokemon.latitude,
          lng: pokemon.longitude,
          image_url: helpers.asset_url("pokeball_marker2.png"),
          info_window: render_to_string(partial: "info_window", locals: { pokemon: pokemon })
        }
      end
    end
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @rental = Rental.new
    @unavailable_dates = Rental.unavailable_dates(@pokemon).to_json
    authorize @pokemon
    if @pokemon.geocoded?
      @markers = [
        {
          lat: @pokemon.latitude,
          lng: @pokemon.longitude,
          image_url: helpers.asset_url("pokeball_marker2.png"),
          info_window: render_to_string(partial: "info_window", locals: { pokemon: @pokemon })
        }
      ]
    end
  end

  def new
    @pokemon = Pokemon.new
    authorize @pokemon
  end

  def create
    @pokemon = Pokemon.new(params_validation)
    @pokemon.user = current_user
    if @pokemon.save
      redirect_to pokemon_path(@pokemon)
    else
      render :new
    end
    authorize @pokemon
  end

  def edit
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
  end

  def update
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
    @pokemon.update(params_validation)
    redirect_to pokemon_path(@pokemon)
  end

  def destroy
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
    @pokemon.destroy
    redirect_to pokemons_path
  end

  private

  def params_validation
    params.require(:pokemon).permit(:name, :special_capacity, :category, :description, :photo, :address)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController


  def show
    # raise
    @rental = Rental.find(params[:id])
    authorize @rental
  end

  def create
    @rental = Rental.new(rental_params)
    @pokemon = Pokemon.find(params[:pokemon_id])
    @rental.pokemon = @pokemon
    @rental.user = current_user
    @rental.save
    authorize @rental
    redirect_to dashboard_booking_path(@rental)
  end

private

  def rental_params
    params.require(:rental).permit(:rental_beginning, :rental_end, :pokemon_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GottaRentEmAll</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>

    <div style="height: 80px">
      <%= render 'shared/navbar' %>
    </div>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/dashboard.html.erb
<%#= image_tag "pokemon_banner.png", style: 'background-size: cover; width: 100%; height: 100%' %>

<div class="background_image_new">
  <div class="container dashboard-title mt-3">
    <p class="font-size-dashboard"><%= "DASHBOARD" %></p>

    <% unless @last_rental.nil? %>
    <p class="text-success" ><%= "Last rental confirmed !" %></p>
    <p class="text-success"><%= "from : #{@last_rental.rental_beginning.strftime('%a %d %b %Y')} to: #{@last_rental.rental_end.strftime('%a %d %b %Y')}" %></p>
    <p class="text-success"> <%= "With #{@last_rental.pokemon.name}" %></p>
    <% end %>

  </div>

  <div data-controller="maindashboard">

    <div class="tab container mt-5 d-flex justify-content-around">
      <button id="button4" class="tablinks tab-button" data-action="click->maindashboard#openTab" data-tab="my-pokemons">MY POKEMONS !</button>
      <button id="button5" class="tablinks tab-button" data-action="click->maindashboard#openTab" data-tab="my-bookings">MY BOOKINGS !</button>
    </div>

    <div id="my-pokemons">
      <div class="container dashboard-part mt-3">
        <%= "MY POKEMONS" %>
      </div>

      <div class="dashboard-block">
        <div class="container">
          <div class="row mt-4 w-100 mx-0">
            <% @pokemons.each do |pokemon| %>
              <div class="col-3 mb-3 px-3">
                <%= link_to pokemon_path(pokemon), id: "card-link" do %>
                  <div class="column bg-white h-100" id="card">
                    <% if pokemon.photo.attached? %>
                      <%= cl_image_tag pokemon.photo.key, height: 300, class: "img-card-top" %>
                    <% else%>
                      <%= "METTRE UNE IMAGE" %>
                    <% end%>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item" style="center" id="pokename"> <%= pokemon.name %></li>
                      <li class="list-group-item">Rating: <%= pokemon.rating %></li>
                      <li class="list-group-item">Last bookings:</li>
                      <% pokemon.rentals.last(3).each do |rental| %>
                      <li class="list-group-item"><%= "#{rental.rental_beginning.strftime('%a %d %b %Y')} to #{rental.rental_end.strftime('%a %d %b %Y')} by #{rental.user.name}" %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <br>
      <div class="container mb-5 center">
        <%=  link_to "Add a Pokemon!", new_pokemon_path, class: "btn-ghost mb-5 align" %>
      </div>
    </div>

    <div id="my-bookings" data-controller="dashboard" class="tabcontent">
      <div class="tab container mt-5 d-flex justify-content-around">
        <button id="button1" class="tablinks tab-button" data-action="click->dashboard#openTab" data-tab="current-bookings">My current bookings</button>
        <button id="button2" class="tablinks tab-button" data-action="click->dashboard#openTab" data-tab="future-bookings">My future bookings</button>
        <button id="button3" class="tablinks tab-button" data-action="click->dashboard#openTab" data-tab="past-bookings">My past bookings</button>
      </div>


      <div id="current-bookings" >
        <div class="container">
          <div class="row mt-4 w-100 mx-0">
            <% current_rentals = @rentals.select { |rental| (rental.rental_end >= Date.today) && (rental.rental_beginning <= Date.today) } %>
            <% current_rentals.each do |rental| %>
              <div class="col-2 mb-3 px-3">
                <%= link_to pokemon_path(rental.pokemon), id: "card-link" do %>
                  <div class="column bg-white h-100" id="card">
                    <% if rental.pokemon.photo.attached? %>
                      <%= cl_image_tag rental.pokemon.photo.key, height: 300, class: "img-card-top" %>
                    <% else%>
                      <%= "METTRE UNE IMAGE" %>
                    <% end%>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item" style="center" id="pokename"> <%= rental.pokemon.name %></li>
                      <li class="list-group-item">Booking:</li>
                      <li class="list-group-item"><%= "#{rental.rental_beginning.strftime('%a %d %b %Y')} to #{rental.rental_end.strftime('%a %d %b %Y')}" %></li>            </ul>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>


      <div id="future-bookings" class="tabcontent">
        <div class="container">
          <div class="row mt-4 w-100 mx-0">
            <% current_rentals = @rentals.select { |rental| rental.rental_beginning > Date.today } %>
            <% current_rentals.each do |rental| %>
              <div class="col-2 mb-3 px-3">
                <%= link_to pokemon_path(rental.pokemon), id: "card-link" do %>
                  <div class="column bg-white h-100" id="card">
                    <% if rental.pokemon.photo.attached? %>
                      <%= cl_image_tag rental.pokemon.photo.key, height: 300, class: "img-card-top" %>
                    <% else%>
                      <%= "METTRE UNE IMAGE" %>
                    <% end%>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item" style="center" id="pokename"> <%= rental.pokemon.name %></li>
                      <li class="list-group-item">Booking:</li>
                      <li class="list-group-item"><%= "#{rental.rental_beginning.strftime('%a %d %b %Y')} to #{rental.rental_end.strftime('%a %d %b %Y')}" %></li>            </ul>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>


      <div id="past-bookings" class="tabcontent">
        <div class="container">
          <div class="row mt-4 w-100 mx-0">
            <% current_rentals = @rentals.select { |rental| rental.rental_end < Date.today } %>
            <% current_rentals.each do |rental| %>
              <div class="col-2 mb-3 px-3">
                <%= link_to pokemon_path(rental.pokemon), id: "card-link" do %>
                  <div class="column bg-white h-100" id="card">
                    <% if rental.pokemon.photo.attached? %>
                      <%= cl_image_tag rental.pokemon.photo.key, height: 300, class: "img-card-top" %>
                    <% else%>
                      <%= "METTRE UNE IMAGE" %>
                    <% end%>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item" style="center" id="pokename"> <%= rental.pokemon.name %></li>
                      <li class="list-group-item">Booking:</li>
                      <li class="list-group-item"><%= "#{rental.rental_beginning.strftime('%a %d %b %Y')} to #{rental.rental_end.strftime('%a %d %b %Y')}" %></li>            </ul>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(transparent, #000), url(https://www.quizexpo.com/wp-content/uploads/2020/02/f74b7a99-02fb-4109-9c35-303c5b3d69bf.jpg-resize-_opacity_100-frame_bg_color_FFF-gravity_center-q_70-preserve_ratio_true-w_2048_.jpg);">
  <div class="center-on-page">
    <%= link_to pokemons_path do %>
      <div class="pokeball">
      <div class="pokeball__button"></div>
      </div>
    <% end %>
  </div>
</div>

app/views/pokemons/_info_window.html.erb
<%= link_to pokemon_path(pokemon) do %>
<div class="window">
<h1> <%= pokemon.name %> </h1>
<p><%= pokemon.address %></p>
<%= cl_image_tag pokemon.photo.key, height: 200, class: "img-card-top"%>
<% end %>
</div>

app/views/pokemons/edit.html.erb
<div class="background_image_new">
  <div class="container container-form">
    <div id="form_new">
      <%= simple_form_for(@pokemon) do |f| %>
        <%= f.input :name %>
        <%= f.input :special_capacity %>
        <%= f.input :category %>
        <%= f.input :description %>
        <%= f.input :photo, as: :file %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/pokemons/index.html.erb
<%= image_tag "pokemon_banner.png", style: 'background-size: cover; width: 100%; height: 100%' %>


  <div class="row mt-3 mx-2 justify-content-center postion-relative">
    <div class="search_poke ">
      <%= form_tag pokemons_path, style:"display: block ruby", method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a pokemon"
      %>
      <%= submit_tag "Search", class:"btn-ghost" %>
        <%= link_to pokemons_path do %>
          <%= image_tag "Reset", :class => "reset"%>
        <% end %>
      <% end %>
    </div>
  </div>


<div class="row mt-4 w-100 mx-0">
  <% @pokemons_list = @pokemons.select { |pokemon| pokemon.user != current_user } %>
  <% @pokemons_list.each do |pokemon| %>
    <div class="col-3 mb-3 px-3">
      <%= link_to pokemon_path(pokemon), id: "card-link" do %>
        <div class="column bg-white h-100" id="card">
          <% if pokemon.photo.attached? %>
            <%= cl_image_tag pokemon.photo.key, height: 300, class: "img-card-top" %>
          <% else%>
            <%= "METTRE UNE IMAGE" %>
          <% end%>
          <ul class="list-group list-group-flush">
            <li class="list-group-item" style="center" id="pokename"> <%= pokemon.name %></li>
            <li class="list-group-item"> <strong>Description:</strong> <%= pokemon.description %> </li>
            <li class="list-group-item"> Special: <%= pokemon.special_capacity %> </li>
            <li class="list-group-item"> Category: <%= pokemon.category %></li>
            <li class="list-group-item">Rating: <%= pokemon.rating %></li>
          </ul>
        </div>
       <% end %>
    </div>
  <% end %>
</div>
<%# <div class="d-flex justify-content"> %>
  <%# <div class="container"> %>
    <%# <img class="pika_gif" src="https://i.pinimg.com/originals/ab/be/28/abbe28a943ed44fcd98452687f7c46c9.gif"> %>
  <%# </div> %>
  <div class="container">
    <div style="width: 100%; height: 600px;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <%# <img class="pika_gif" src="https://i.pinimg.com/originals/ab/be/28/abbe28a943ed44fcd98452687f7c46c9.gif"> %>
  </div>
  <%# <div class="d-flex space-between">
    <img class="pika_gif" src="https://i.pinimg.com/originals/ab/be/28/abbe28a943ed44fcd98452687f7c46c9.gif">
    <img class="pika_gif" src="https://i.pinimg.com/originals/ab/be/28/abbe28a943ed44fcd98452687f7c46c9.gif">
  </div> %>
</div>
<div class="container">
  <div class="row">
    <img class="pika2", src="https://i.pinimg.com/originals/ab/be/28/abbe28a943ed44fcd98452687f7c46c9.gif">
  </div>
</div>
    <%# <img class="pika_gif" src="https://c.tenor.com/74l5y1hUdtwAAAAi/pokemon.gif"> %>
<%# </div> %>

app/views/pokemons/new.html.erb
<div class="background_image_new">
  <div class="container container-form">
    <div id="form_new">
      <%= simple_form_for(@pokemon) do |f| %>
        <%= f.input :name %>
        <%= f.input :special_capacity %>
        <%= f.input :category %>
        <%= f.input :description %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Add my pokemon !", class: "btn-ghost" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pokemons/show.html.erb
<div class="background_image_new">
  <div class="container">
    <div class="row d-flex mt-5" style="height:55vh">
      <div class="col-sm-6 position-relative" style="height:55vh">
        <p class="text-center position-absolute  bg-danger p-1" style="transform:rotate(-25deg); top:15px; left:-20px; color:white"><%= @pokemon.name %></p>
        <div class="d-flex justify-content-center"  style="height:55vh">
          <div class="card-poke">
            <div class="m-3 p-3 h-50">
              <%= cl_image_tag @pokemon.photo.key, class: "poke_img mt-3" %>
              <div class="card-product-infos h-50 px-5 pb-0 pt-3 mt-5">
            <%# <p>Rating : = @pokemon.rating</p> %>
                <p>Name : <%= @pokemon.name%></p>
                <p>Special capacity: <%= @pokemon.special_capacity %></p>
                <p>Category : <%= @pokemon.category %></p>
                <p>Description : <%= @pokemon.description %></p>
                <p>Trainer : <%= @pokemon.user.name %></p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-6" style="height:55vh">
        <div class="card-poke d-flex flex-column"  style="height:55vh">
            <div style="width: 100%; height: 600px;"
              data-controller="mapbox"
              data-mapbox-markers-value="<%= @markers.to_json %>"
              data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
        </div>
      </div>
    </div>


  <% if !policy(@pokemon).edit? %>
    <div id = "booking-dates" class="row mx-0 my-5 p-5 card-poke" data-unavailable="<%= @unavailable_dates %>" >
      <%= simple_form_for([@pokemon, @rental]) do |f| %>
        <div class="d-flex justify-content-around align-items-center">
          <div>
            <%= f.input :rental_beginning, as: :string, required: false, input_html: {class: "datepicker", id:"start_date"} %>
          </div>
          <div>
            <%= f.input :rental_end, as: :string, required: false, input_html: {class: "datepicker", id:"end_date"} %>
          </div>
          <div class="d-none" id="submit_form">
            <%= f.submit %>
          </div>
          <div>
            <button id="sweet-alert-demo", class="mt-3 btn-ghost">Rent me !</button>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  </div>
</div>
<br>
<br>
<br>
<br>
  <div class="container d-flex">
    <div class="d-flex">
      <% if policy(@pokemon).edit? %>
      <div>
        <%= link_to "Edit my pokemon", edit_pokemon_path(@pokemon), class: "btn-ghost" %>
      </div>
      <div>
        <%= link_to "Delete my pokemon", pokemon_path(@pokemon), class: "btn-ghost", method: :delete, data: { confirm: "Are you sure?", disable_with: "Processing..." } %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rentals/create.html.erb
<h1>Rentals#create</h1>
<p>Find me in app/views/rentals/create.html.erb</p>

app/views/rentals/show.html.erb
<h1>confirmation de commande</h1>

<p>ICI</p>
<p>ICI</p>
<p>ICI</p>
<p>ICI</p>
<p>ICI</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="fixed-top navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <%= image_tag "logo", width:50 %>
    <% end %>
    <div class="d-flex justify-content-center align-items-center" id="navbar-center">
      <img class="drac_gif" src="https://giffiles.alphacoders.com/139/13944.gif">
      <h1 id="navbar-title">GOTTA RENT EM ALL</h1>
      <img class="drac_gif" src="https://giffiles.alphacoders.com/139/13944.gif">
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
              <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to current_user.email, "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatarfiles.alphacoders.com/893/thumb-1920-89303.gif" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%#= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>